### ISSUE TITLE
MFA question

### ISSUE THREAD

**Issue by sharpsan** [scottbonline/sense#70]
Over at Home Assistant, some users have started getting an error during login when MFA is enabled.  

I have been looking at the code trying to figure out where the function `fetch_discovered_devices` originates.  I see that it is called 3 times in `asyncsenseable.py`.  Can you point me in the right direction?

Here's the full log for reference:

```
Logger: homeassistant.components.sense.config_flow
Source: components/sense/config_flow.py:108
integration: Sense (documentation, issues)
First occurred: 12:06:10 AM (1 occurrences)
Last logged: 12:06:10 AM

Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sense/config_flow.py", line 108, in async_step_validation
    await self._gateway.validate_mfa(user_input[CONF_CODE])
  File "/usr/local/lib/python3.12/site-packages/sense_energy/asyncsenseable.py", line 120, in validate_mfa
    await self.fetch_discovered_devices()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ASyncSenseable' object has no attribute 'fetch_discovered_devices'. Did you mean: 'get_discovered_device_data'?
```

**Comment by kbickar** [comment]
That should be `fetch_devices` I've updated it
